# Packages to install on new machines

[manual]
packages = [
anaconda3, # can't live without one
nodejs,
]


[apt-packages]
packages = [
kitty,
python3-pip,
libgtk-3-dev,
]

[python]
packages = [
ranger-fm
]

[node-git]
    [node.mojibar]
    github = 'git@github.com:dumbPy/mojibar.git'
    command = 'npm install'
    
[node]
packages = [
]

[git]
    [git.dragon]
    github = 'https://github.com/mwh/dragon'
    command = 'make install'
